In [1]:

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("leetcode_dataset - lc.csv")

In [4]:
df.head()

,id,title,description,is_premium,difficulty,solution_link,acceptance_rate,frequency,url,discuss_count,accepted,submissions,companies,related_topics,likes,dislikes,rating,asked_by_faang,similar_questions
0,1,Two Sum,Given an array of integers `nums` and an integ...,0,Easy,/articles/two-sum,46.7,100.0,https://leetcode.com/problems/two-sum,999,4.1M,8.7M,"Amazon,Google,Apple,Adobe,Microsoft,Bloomberg,...","Array,Hash Table",20217,712,97,1,"[3Sum, /problems/3sum/, Medium], [4Sum, /probl..."
1,2,Add Two Numbers,You are given two non-empty linked lists repre...,0,Medium,/articles/add-two-numbers,35.7,93.1,https://leetcode.com/problems/add-two-numbers,999,1.9M,5.2M,"Bloomberg,Microsoft,Amazon,Google,Facebook,App...","Linked List,Math,Recursion",11350,2704,81,1,"[Multiply Strings, /problems/multiply-strings/..."
2,3,Longest Substring Without Repeating Characters,"Given a string `s`, find the length of the lon...",0,Medium,/articles/longest-substring-without-repeating-...,31.5,90.9,https://leetcode.com/problems/longest-substrin...,999,2.1M,6.7M,"Amazon,Bloomberg,Microsoft,Facebook,Apple,Adob...","Hash Table,Two Pointers,String,Sliding Window",13810,714,95,1,[Longest Substring with At Most Two Distinct C...
3,4,Median of Two Sorted Arrays,Given two sorted arrays `nums1` and `nums2` of...,0,Hard,/articles/median-of-two-sorted-arrays,31.4,86.2,https://leetcode.com/problems/median-of-two-so...,999,904.7K,2.9M,"Amazon,Goldman Sachs,Facebook,Microsoft,Apple,...","Array,Binary Search,Divide and Conquer",9665,1486,87,1,NaN
4,5,Longest Palindromic Substring,"Given a string `s`, return the longest palindr...",0,Medium,/articles/longest-palindromic-substring,30.6,84.7,https://leetcode.com/problems/longest-palindro...,999,1.3M,4.1M,"Amazon,Microsoft,Wayfair,Facebook,Adobe,eBay,G...","String,Dynamic Programming",10271,670,94,1,"[Shortest Palindrome, /problems/shortest-palin..."

In [7]:
df.columns

Index(['id', 'title', 'description', 'is_premium', 'difficulty',
       'solution_link', 'acceptance_rate', 'frequency', 'url', 'discuss_count',
       'accepted', 'submissions', 'companies', 'related_topics', 'likes',
       'dislikes', 'rating', 'asked_by_faang', 'similar_questions'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1825 non-null   int64
 1   title              1825 non-null   object
 2   description        1825 non-null   object
 3   is_premium         1825 non-null   int64
 4   difficulty         1825 non-null   object
 5   solution_link      987 non-null    object
 6   acceptance_rate    1825 non-null   float64
 7   frequency          1825 non-null   float64
 8   url                1825 non-null   object
 9   discuss_count      1825 non-null   int64
 10  accepted           1825 non-null   object
 11  submissions        1825 non-null   object
 12  companies          1749 non-null   object
 13  related_topics     1571 non-null   object
 14  likes              1825 non-null   int64
 15  dislikes           1825 non-null   int64
 16  rating             1825 non-null   int64
 17  asked_by_faang     1825 non-null   int64
 18  similar_questions  745 non-null    object
dtypes: float64(2), int64(7), object(10)
memory usage: 271.0+ KB

In [9]:
df.shape

(1825, 19)

In [10]:
df.isnull().sum()

id                      0
title                   0
description             0
is_premium              0
difficulty              0
solution_link         838
acceptance_rate         0
frequency               0
url                     0
discuss_count           0
accepted                0
submissions             0
companies              76
related_topics        254
likes                   0
dislikes                0
rating                  0
asked_by_faang          0
similar_questions    1080
dtype: int64

In [11]:
df = df.drop_duplicates().reset_index(drop = True)

In [14]:
df = df[['title', 'description', 'difficulty',
       'frequency', 'url', 'companies', 'related_topics', 'likes',
       'dislikes', 'rating', 'asked_by_faang']]

In [15]:
df

,title,description,difficulty,frequency,url,companies,related_topics,likes,dislikes,rating,asked_by_faang
0,Two Sum,Given an array of integers `nums` and an integ...,Easy,100.0,https://leetcode.com/problems/two-sum,"Amazon,Google,Apple,Adobe,Microsoft,Bloomberg,...","Array,Hash Table",20217,712,97,1
1,Add Two Numbers,You are given two non-empty linked lists repre...,Medium,93.1,https://leetcode.com/problems/add-two-numbers,"Bloomberg,Microsoft,Amazon,Google,Facebook,App...","Linked List,Math,Recursion",11350,2704,81,1
2,Longest Substring Without Repeating Characters,"Given a string `s`, find the length of the lon...",Medium,90.9,https://leetcode.com/problems/longest-substrin...,"Amazon,Bloomberg,Microsoft,Facebook,Apple,Adob...","Hash Table,Two Pointers,String,Sliding Window",13810,714,95,1
3,Median of Two Sorted Arrays,Given two sorted arrays `nums1` and `nums2` of...,Hard,86.2,https://leetcode.com/problems/median-of-two-so...,"Amazon,Goldman Sachs,Facebook,Microsoft,Apple,...","Array,Binary Search,Divide and Conquer",9665,1486,87,1
4,Longest Palindromic Substring,"Given a string `s`, return the longest palindr...",Medium,84.7,https://leetcode.com/problems/longest-palindro...,"Amazon,Microsoft,Wayfair,Facebook,Adobe,eBay,G...","String,Dynamic Programming",10271,670,94,1
...,...,...,...,...,...,...,...,...,...,...,...
1820,Find Customers With Positive Revenue this Year,SQL Schema,Easy,0.0,https://leetcode.com/problems/find-customers-w...,Google,NaN,2,2,50,1
1821,Sign of the Product of an Array,There is a function `signFunc(x)` that returns...,Easy,0.0,https://leetcode.com/problems/sign-of-the-prod...,Microsoft,Math,37,4,90,0
1822,Find the Winner of the Circular Game,There are `n` friends that are playing a game....,Medium,0.0,https://leetcode.com/problems/find-the-winner-...,Bloomberg,Array,81,4,95,0
1823,Minimum Sideway Jumps,There is a 3 lane road of length `n` that cons...,Medium,0.0,https://leetcode.com/problems/minimum-sideway-...,Pony.ai,"Dynamic Programming,Breadth-first Search",147,8,95,0
1824,Finding MK Average,"You are given two integers, `m` and `k`, and a...",Hard,0.0,https://leetcode.com/problems/finding-mk-average,Google,"Heap,Design,Queue",52,43,55,1

In [16]:
df.isnull().sum()

title               0
description         0
difficulty          0
frequency           0
url                 0
companies          76
related_topics    254
likes               0
dislikes            0
rating              0
asked_by_faang      0
dtype: int64

In [17]:
df['related_topics'] = df['related_topics'].fillna('')

In [18]:
df['companies'] = df['companies'].fillna('')

In [19]:
df.isnull().sum()

title             0
description       0
difficulty        0
frequency         0
url               0
companies         0
related_topics    0
likes             0
dislikes          0
rating            0
asked_by_faang    0
dtype: int64

In [20]:
df.columns

Index(['title', 'description', 'difficulty', 'frequency', 'url', 'companies',
       'related_topics', 'likes', 'dislikes', 'rating', 'asked_by_faang'],
      dtype='object')

In [21]:
df['tags'] = df['description']+ " " + df['difficulty'] +" "+ df['companies']+" "+ df['related_topics']

In [22]:
df.head()

,title,description,difficulty,frequency,url,companies,related_topics,likes,dislikes,rating,asked_by_faang,tags
0,Two Sum,Given an array of integers `nums` and an integ...,Easy,100.0,https://leetcode.com/problems/two-sum,"Amazon,Google,Apple,Adobe,Microsoft,Bloomberg,...","Array,Hash Table",20217,712,97,1,Given an array of integers `nums` and an integ...
1,Add Two Numbers,You are given two non-empty linked lists repre...,Medium,93.1,https://leetcode.com/problems/add-two-numbers,"Bloomberg,Microsoft,Amazon,Google,Facebook,App...","Linked List,Math,Recursion",11350,2704,81,1,You are given two non-empty linked lists repre...
2,Longest Substring Without Repeating Characters,"Given a string `s`, find the length of the lon...",Medium,90.9,https://leetcode.com/problems/longest-substrin...,"Amazon,Bloomberg,Microsoft,Facebook,Apple,Adob...","Hash Table,Two Pointers,String,Sliding Window",13810,714,95,1,"Given a string `s`, find the length of the lon..."
3,Median of Two Sorted Arrays,Given two sorted arrays `nums1` and `nums2` of...,Hard,86.2,https://leetcode.com/problems/median-of-two-so...,"Amazon,Goldman Sachs,Facebook,Microsoft,Apple,...","Array,Binary Search,Divide and Conquer",9665,1486,87,1,Given two sorted arrays `nums1` and `nums2` of...
4,Longest Palindromic Substring,"Given a string `s`, return the longest palindr...",Medium,84.7,https://leetcode.com/problems/longest-palindro...,"Amazon,Microsoft,Wayfair,Facebook,Adobe,eBay,G...","String,Dynamic Programming",10271,670,94,1,"Given a string `s`, return the longest palindr..."

In [23]:
df['tags'][1]

'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.\n\nYou may assume the two numbers do not contain any leading zero, except the number 0 itself.\n\n\nExample 1:\nInput: l1 = [2,4,3], l2 = [5,6,4]\nOutput: [7,0,8]\nExplanation: 342 + 465 = 807.\n\n\nExample 2:\nInput: l1 = [0], l2 = [0]\nOutput: [0]\n\nExample 3:\nInput: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]\nOutput: [8,9,9,9,0,0,0,1]\n\nConstraints:\nThe number of nodes in each linked list is in the range `[1, 100]`.\n\n`0 <= Node.val <= 9`\nIt is guaranteed that the list represents a number that does not have leading zeros. Medium Bloomberg,Microsoft,Amazon,Google,Facebook,Apple,Adobe,Paypal,Coupang,Oracle,Uber,VMware,Yahoo Linked List,Math,Recursion'

In [25]:
!pip install nltk

Collecting nltk

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ACER\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ACER\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ACER\anaconda3\Lib\site-packages)

  Downloading nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\acer\anaconda3\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\acer\anaconda3\lib\site-packages (from nltk) (1.5.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.2.28-cp313-cp313-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in c:\users\acer\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\acer\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.3-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.3 MB/s eta 0:00:00
Downloading regex-2026.2.28-cp313-cp313-win_amd64.whl (277 kB)
Installing collected packages: regex, nltk

   ---------------------------------------- 0/2 [regex]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed nltk-3.9.3 regex-2026.2.28

In [26]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [27]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...

True

In [28]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [32]:
def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)   # keeps only alphabets

    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [33]:
df['tags'] = df['tags'].apply(preprocess_text)

In [34]:
df['tags'][1]

'given two nonempty linked list representing two nonnegative integer digit stored reverse order node contains single digit add two number return sum linked list may assume two number contain leading zero except number example input l l output explanation example input l l output example input l l output constraint number node linked list range nodeval guaranteed list represents number leading zero medium bloombergmicrosoftamazongooglefacebookappleadobepaypalcoupangoracleubervmwareyahoo linked listmathrecursion'

In [35]:
df = df.reset_index(drop = True)

In [36]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Two Sum                                              0
Add Two Numbers                                      1
Longest Substring Without Repeating Characters       2
Median of Two Sorted Arrays                          3
Longest Palindromic Substring                        4
                                                  ...
Find Customers With Positive Revenue this Year    1820
Sign of the Product of an Array                   1821
Find the Winner of the Circular Game              1822
Minimum Sideway Jumps                             1823
Finding MK Average                                1824
Length: 1825, dtype: int64

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [39]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Problem not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [42]:
recommend('Two Sum',5)

34                                 Search Insert Position
703                                         Binary Search
258                                          3Sum Smaller
17                                                   4Sum
1545    Maximum Number of Non-Overlapping Subarrays Wi...
Name: title, dtype: object

In [43]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))